baseURL = "https://eu19.tracking.exposed/"
languageCode = "en-us"
title = "eu19 Tracking Expose"
theme = "eutrex"
[permalinks]
  posts = "/:slug/"

#sectionPagesMenu = "main"

menu = ["main", "footer"]

 [[menu.main]]
    page = "get-the-extension"
    identifier = "get-the-extension"
    name = "Get the extension"
    url = "/page/get-the-extension/"
    weight = -100
 [[menu.main]]
    page = "faqs"
    identifier = "faqs"
    name = "FAQ"
    url = "/faq/"
    weight = -110


 [[menu.footer]]
    page = "get-the-extension"
    identifier = "get-the-extension"
    name = "Get the extension"
    url = "/page/get-the-extension/"
    weight = -110