baseURL = "/"
languageCode = "en-us"
title = "eu19 Tracking Expose"
theme = "eutrex"
enableRobotsTXT = true
canonifyURLs = true
[params]
  description = "EU election 2019 Tracking expose. A collaborative observatory of algorithm influences, and few citizen driven solutions."

[permalinks]
  posts = "/:slug/"

#sectionPagesMenu = "main"

menu = ["main", "footer"]

 [[menu.main]]
    page = "Researcher"
    identifier = "researcher"
    name = "Researcher"
    url = "/page/researcher/"
    weight = -110
 [[menu.main]]
    page = "Individual"
    identifier = "Individual"
    name = "Individual"
    url = "/page/individual/"
    weight = -120
 [[menu.main]]
    page = "Candidate"
    identifier = "candidate"
    name = "Candidates"
    url = "/page/candidate/"
    weight = -130
 [[menu.main]]
    page = "Ethos"
    identifier = "ethos"
    name = "Goals and ethos"
    url = "/page/ethos/"
    weight = -140
 [[menu.main]]
    page = "RSS"
#    parent = "the parent element identifier"
    identifier = "rss"
    name = "Watch events"
    url = "/page/rss/"
    weight = -150


 [[menu.footer]]
    page = "get-the-extension"
    identifier = "get-the-extension"
    name = "Get the extension"
    url = "/page/get-the-extension/"
    weight = -110
 [[menu.footer]]
     page = "Researcher"
     identifier = "researcher"
     name = "Researcher"
     url = "/page/researcher/"
     weight = -120
 [[menu.footer]]
     page = "Individual"
     identifier = "individual"
     name = "Individual"
     url = "/page/individual/"
     weight = -130
 [[menu.footer]]
     page = "Candidate"
     identifier = "candidate"
     name = "Candidates"
     url = "/page/candidate/"
     weight = -140
 [[menu.footer]]
     page = "Ethos"
     identifier = "ethos"
     name = "Goals and ethos"
     url = "/page/ethos/"
     weight = -150
 [[menu.footer]]
     page = "RSS"
     identifier = "rss"
     name = "Watch events horizontally"
     url = "/page/rss/"
     weight = -160